apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratingroost-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ratingroost
  template:
    metadata:
      labels:
        app: ratingroost
    spec:
      containers:
      - name: ratingroost
        image: ironthor/ratingroost:0.0.1
        ports:
        - containerPort: 5000

